parameters:
#    parameter_name: value

services:
    measurement_service:
        class: AppBundle\Service\MeasurementService
        arguments: ["@doctrine.orm.entity_manager", "@device_api_service"]

    # Just for debugging purpose
    device_api_service_mock:
        class: AppBundle\Service\DeviceAPIServiceMock

    device_api_service:
        class: AppBundle\Service\DeviceAPIService
        arguments: ["@device_api_browser", "@logger"]

    device_api_browser:
        class: Buzz\Browser
        arguments: ["@buzz.client", "@buzz.message_factory"]

    validator.device_connectivity_validator:
        class: AppBundle\Constraint\DeviceConnectivityConstraintValidator
        arguments: ["@device_api_service"]
        tags:
            - { name: validator.constraint_validator, alias: device_connectivity_validator }

    validator.device_authentication_validator:
            class: AppBundle\Constraint\DeviceAuthenticationConstraintValidator
            arguments: ["@device_api_service"]
            tags:
                - { name: validator.constraint_validator, alias: device_authentication_validator }

