parameters:
#    parameter_name: value

services:
    # Memcached
    memcached:
        class: Memcached
        calls:
            - [ addServer, ["%memcached_host%", "%memcached_port%"] ]
    memcached_cache:
        class: Doctrine\Common\Cache\MemcachedCache
        calls:
            - [ setMemcached, [@memcached] ]

    # Measurement service
    measurement_service:
        class: AppBundle\Service\MeasurementService
        arguments: ["@doctrine.orm.entity_manager", "@device_api_service"]

    # Measuremenr daemen service
    measurement_daemon_service:
        class: AppBundle\Service\MeasurementDaemonService
        arguments: ["@doctrine.orm.entity_manager", "@buzz", "@logger"]

    # Health check
    health_check_service:
        class: AppBundle\Service\HealthCheckService
        arguments: ["@notification_service", "@doctrine.orm.entity_manager", "@measurement_daemon_service",  "@device_api_service"]

    # Device API
    device_api_service:
        class: AppBundle\Service\DeviceAPIService
        # Just for debugging purpose
        # class: AppBundle\Service\DeviceAPIServiceMock
        arguments: ["@buzz", "@logger"]

    # Notifications
    notification_service:
        class: AppBundle\Service\NotificationServiceThrottle
        arguments: ["@notification_service_composite", "@memcached_cache"]

    notification_service_composite:
        class: AppBundle\Service\NotificationServiceComposite
        calls:
            - [add, ["@notification_service_mail"]]

    notification_service_mail:
        class: AppBundle\Service\NotificationServiceMail
        arguments: ["@mailer", "%notifications_mail_sender%", "%notifications_mail_receiver%"]


    # Custom validator services
    validator.device_connectivity_validator:
        class: AppBundle\Constraint\DeviceConnectivityConstraintValidator
        arguments: ["@device_api_service"]
        tags:
            - { name: validator.constraint_validator, alias: device_connectivity_validator }

    validator.device_authentication_validator:
            class: AppBundle\Constraint\DeviceAuthenticationConstraintValidator
            arguments: ["@device_api_service"]
            tags:
                - { name: validator.constraint_validator, alias: device_authentication_validator }

    validator.device_in_use_validator:
                class: AppBundle\Constraint\DeviceInUseConstraintValidator
                arguments: ["@doctrine.orm.entity_manager"]
                tags:
                    - { name: validator.constraint_validator, alias: device_in_use_validator }
