parameters:
#    parameter_name: value

services:
    measurement_service:
        class: AppBundle\Service\MeasurementService
        arguments: ["@doctrine.orm.entity_manager", "@device_service_mock"]

    device_service_mock:
        class: AppBundle\Service\DeviceServiceMock

