<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends EntityRepository
{
    /**
     * Count all Devices.
     *
     * @return int
     */
    public function countAll()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select($qb->expr()->count('d'))
            ->from($this->_entityName, 'd');

        return (int)$qb->getQuery()->getSingleScalarResult();
    }

    /**
     * Just returns one "random" device.
     *
     * @return array
     */
    public function getOne()
    {
        $entities = $this->findBy([], [], 1);
        return isset($entities[0]) ? $entities[0] : null;
    }
}
