<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MeasurementProbeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeasurementProbeRepository extends EntityRepository
{
}
