<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MeasurementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeasurementRepository extends EntityRepository
{
    const LIMIT = 10;

    /**
     * Count all Measurements.
     *
     * @return int
     */
    public function countAll()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select($qb->expr()->count('d'))
            ->from($this->_entityName, 'd');

        return (int)$qb->getQuery()->getSingleScalarResult();
    }

    /**
     * Retrive all active measurements
     *
     * @return array
     */
    public function getActive()
    {
        $em = $this->getEntityManager();

        $entities = $this->findBy(
            array('end' => null),
            array('id'=>'DESC')
        );

        return $entities;
    }

    /**
     * Decides wether the given device already is in use or not.
     *
     * @param Device $device
     * @param Measurement $measurement
     * @return bool
     */
    public function inUse(Device $device, Measurement $measurement = null)
    {
        $id = $device->getId();

        /** @var Measurement $tmpMeasurement */
        foreach ($this->getActive() as $tmpMeasurement) {
            if ($id === $tmpMeasurement->getDevice()->getId()
                && (!$measurement || $measurement->getId() !== $tmpMeasurement->getId())
            ) {
                return true;
            }
        }

        return false;
    }

    /**
     * Returns one page of the measurement history.
     *
     * @param $page
     * @return Paginator
     */
    public function history($page)
    {
        $page = $page ? $page : 1;
        $offset = ($page - 1) * self::LIMIT;

        $dql = "SELECT m FROM AppBundle\\Entity\\Measurement m ORDER BY m.id DESC";
        $query = $this->getEntityManager()->createQuery($dql)
            ->setFirstResult($offset)
            ->setMaxResults(self::LIMIT);

        $paginator = new Paginator($query);

        return $paginator;
    }

    /**
     * Returns the limit for the pager.
     *
     * @return int
     */
    public function getLimit()
    {
        return self::LIMIT;
    }
}
