<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MeasurementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeasurementRepository extends EntityRepository
{
    /**
     * Count all Measurements.
     *
     * @return int
     */
    public function countAll()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select($qb->expr()->count('d'))
            ->from($this->_entityName, 'd');

        return (int)$qb->getQuery()->getSingleScalarResult();
    }

    /**
     * Retrive all active measurements
     *
     * @return array
     */
    public function getActive()
    {
        $em = $this->getEntityManager();

        $entities = $em->getRepository('AppBundle:Measurement')->findBy(
            array('end' => null),
            array('id'=>'DESC')
        );

        return $entities;
    }
}
